# A recurring workflow which updates the passing/failing/skipped integration tests for Turbopack.
name: Update Turbopack test manifest

on:
  schedule:
    # Every day at 9AM https://crontab.guru/#0_9_*_*_*
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update_manifest:
    name: Update and upload Turbopack test manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Commits made with the default `GITHUB_TOKEN` won't trigger workflows.
          # See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true

      - run: corepack enable

      - name: Install dependencies
        shell: bash
        run: pnpm i

      - name: Create Pull Request
        shell: bash
        run: node scripts/automated-update-workflow.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_PULL_REQUESTS }}
          BRANCH_NAME: turbopack-manifest
          SCRIPT: test/build-turbopack-tests-manifest.js
          PR_TITLE: Update Turbopack test manifest
          PR_BODY: This auto-generated PR updates the integration test manifest used when testing Turbopack.
