import type { Metadata, Viewport } from "next";

import "./globals.css";
import "@/public/icomoon/style.css";

import { i18n } from "@/i18n-config";
import { Providers } from "@/lib/Providers";
import localFont from "next/font/local";
import { Suspense } from "react";
import Script from "next/script";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const customFontIcon = localFont({
  src: "../public/icomoon/fonts/custom-icon-font.woff",
  display: "swap",
  variable: "--custom-font-icon",
});

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Next14-PWA",
  description: "Generated by Amir Ali Azimloo",
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html
      lang={params.lang}
      dir={params.lang == "fa" ? "rtl" : "ltr"}
      className={customFontIcon.variable}
    >
      <body className="w-full bg-neutral-50">
        {/* <TestProvider> */}
        <div className="w-full px-1 h-full">
          <Providers>
            {/* <LocaleSwitcher /> */}
            <Suspense>{children}</Suspense>
          </Providers>
        </div>
        {/* </TestProvider> */}

        <Script
          id="google-tag-manager"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-WHSW9262');
          `,
          }}
        />

        <noscript
          dangerouslySetInnerHTML={{
            __html: `
           <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P2RVH9TJ"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>
        `,
          }}
        />
      </body>
    </html>
  );
}
