import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  manifest:"/manifest.json",
  title: 'Next14-PWA',
  description: 'Generated by Amir Ali Azimloo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body >{children}</body>
    </html>
  )
}
