import type { Metadata, Viewport } from 'next'
import '../globals.css'


import { i18n } from '@/i18n-config'
import { Providers } from '@/lib/Providers'
import LocaleSwitcher from '@/components/locale-switcher'
import { AuthProvider } from '@/context/AuthContext'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export const metadata: Metadata = {
  manifest:"/manifest.json",
  title: 'Next14-PWA',
  description: 'Generated by Amir Ali Azimloo',
}

export const viewport: Viewport = {
  themeColor : "#FFFFFF"
}

export default function RootLayout({ 
  children,
  params
}: { 
  children: React.ReactNode;
  params: { lang: string }
}) { 
  return (
    <html lang={params.lang} dir={params.lang == "fa" ? "rtl" : "ltr"} >
      <body className='w-full bg-neutral-50' >
      <AuthProvider>
      <div className='w-full px-1 h-full' >
      <Providers>
       <LocaleSwitcher />
        {children}
      </Providers>
      </div>
      </AuthProvider>
      </body>
    </html>
  )
}
