[package]
edition = "2018"
name = "next-swc"
version = "0.0.0"
publish = false

[features]
plugin = ["turbopack-binding/__swc_core_binding_napi_plugin"]

[lints]
workspace = true

[dependencies]
chrono = "0.4"
convert_case = "0.5.0"
easy-error = "1.0.0"
either = "1"
fxhash = "0.2.1"
hex = "0.4.3"
once_cell = { workspace = true }
pathdiff = "0.2.0"
regex = "1.5"
rustc-hash = "1"
serde = "1"
serde_json = "1"
sha1 = "0.10.1"
tracing = { version = "0.1.37" }

next-transform-dynamic = { workspace = true }
next-transform-font = { workspace = true }

turbopack-binding = { workspace = true, features = [
  "__swc_core",
  "__swc_core_next_core",
  "__swc_transform_styled_jsx",
  "__swc_transform_emotion",
  "__swc_transform_styled_components",
  "__swc_transform_modularize_imports",
  "__swc_transform_relay",
] }
react_remove_properties = "0.18.0"
remove_console = "0.19.0"

[dev-dependencies]
turbopack-binding = { workspace = true, features = [
  "__swc_core_testing_transform",
  "__swc_testing",
] }

walkdir = "2.3.2"
