[package]
name = "next-transform-strip-page-exports"
version = "0.1.0"
description = "SWC transform to selectively strip Next.js page data or default exports"
license = "MPL-2.0"
edition = "2021"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
rustc-hash = { workspace = true }
tracing = { workspace = true }

swc_core = { workspace = true, features = [
  "ecma_ast",
  "common",
  "common_concurrent",
  "common_sourcemap",
  "ecma_codegen",
  "ecma_parser",
  "ecma_preset_env",
  "ecma_transforms",
  "ecma_transforms_module",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_quote",
  "ecma_visit",
  "ecma_visit_path",
  "ecma_utils",
  "testing",
  "base",
] }

[dev-dependencies]
swc_core = { workspace = true, features = ["testing_transform"] }
testing = { workspace = true }
